### ISSUE TITLE
Problem with authorization when replicaSet is enabled

### ISSUE THREAD

**Issue by jivco** [hypertrace/mongodb#5]
Hi,

I'm trying to password protect a replica set but it is not working. When I log in the master pod I can see that  MONGODB_REPLICA_SET_KEY env is set but in /etc/mongodb/mongodb.conf there is no record for keyFile. The rs.status() error is "no replset config has been received".

Here is values.yaml

```
nameOverride: ""
fullnameOverride: ""

image:
  repository: mongo
  tag: 4.4.0
  pullPolicy: "IfNotPresent"

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""


usePassword: true


mongodbRootUsername: root
mongodbRootPassword: "pass"


securityContext:
  enabled: false



service:
  name: ""
  annotations: {}
  type: ClusterIP
  clusterIP: ""
  port: 27017
  nodePort: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []


replicaSet:
  enabled: true
  name: rs0
  enableMajorityReadConcern: false
  key: ""


  replicas:
    secondary: 1
    arbiter: 1


  podDisruptionBudget:
    enabled: false
    minAvailable:
      secondary: 1
      arbiter: 1
    maxUnavailable:
      secondary: ""
      arbiter: ""


annotations: {}


labels: {}


podAnnotations: {}


podLabels: {}


resources: {}


nodeSelector: {}


nodeSelectorSecondary: {}


nodeSelectorArbiter: {}


affinity: {}


affinitySecondary: {}


affinityArbiter: {}


tolerations: []


updateStrategy:
  type: RollingUpdate


persistence:
  mountPath: /data/db
  subPath: ""
  storageClassName: "standard"
  accessModes: ["ReadWriteOnce"]
  size: 2Gi


livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1


storageclass:
  enabled: true
  name: mongo
  annotations: {}
  provisioner: kubernetes.io/gce-pd
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    type: pd-standard

config:
  storage:
    directoryPerDB: false
    journal:
      enabled: true
  systemLog:
    verbosity: 0
  security:
    authorization: enabled
  net:
    ipv6: false
    bindIpAll: true

exporter:
  enabled: false

  affinity: {}

  annotations: {}

  extraArgs:
  - --collect.collection
  - --collect.database
  - --collect.indexusage
  - --collect.topmetrics
  - --collect.connpoolstats

  image:
    pullPolicy: IfNotPresent
    repository: ssheehy/mongodb-exporter
    tag: 0.10.0

  imagePullSecrets: []

  livenessProbe:
    httpGet:
      path: /
      port: metrics
    initialDelaySeconds: 10


  mongodb:
    uri: mongo:27017

  nodeSelector: {}

  podAnnotations: {}


  port: "9216"

  priorityClassName: ""

  readinessProbe:
    httpGet:
      path: /
      port: metrics
    initialDelaySeconds: 10

  replicas: 1

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi


  env: {}

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["all"]
    readOnlyRootFilesystem: true
    runAsGroup: 10000
    runAsNonRoot: true
    runAsUser: 10000

  service:
    annotations: {}
    port: 9216
    type: ClusterIP

  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    secure: false
    tlsConfig: {}
    namespace:
    additionalLabels: {}

  tolerations: []

  dashboard:
    enabled: false
    namespace: monitoring
    annotations: {}

  prometheusrule:
    enabled: false
    annotations: {}

backup:
  enabled: false
  schedule: "0 4 * * *"
  startingDeadlineSeconds: 86400
  concurrencyPolicy: Forbid
  image:
    repository: "hypertrace/mongodb-backup"
    pullPolicy: "IfNotPresent"
  imagePullSecrets: []
  mongodb:
    uri: "mongo://mongodb:27017"
  cluster: "test"
  gcloud: {}
  affinity: {}
  nodeSelector: {}
  securityContext: {}
  tolerations: []
  podAnnotations: {}
```
